apiVersion: apps/v1
kind: Deployment
metadata:
  name: sre-observability
  namespace: argocd
spec:
  selector:
      matchLabels:
        app: sre-observability
  replicas: 5
  template:
    metadata:
      labels:
        app: sre-observability
    spec:
      containers:
        - name: sre-observability
          image: rafacamppos/sre-app
          imagePullPolicy: Always
          ports:
          - containerPort: 80
          readinessProbe:
            initialDelaySeconds: 1
            successThreshold: 1
            failureThreshold: 1
            periodSeconds: 2
            timeoutSeconds: 1
            httpGet:
              path: /
              port: 80
          