apiVersion: apps/v1
kind: Deployment
metadata:
  name: sre-observability
  namespace: sre
spec:
  selector:
      matchLabels:
        app: sre-observability
  replicas: 2
  template:
    metadata:
      labels:
        app: sre-observability
    spec:
      containers:
        - name: sre-observability
          image: rafacamppos/sre-app
          imagePullPolicy: Always
          ports:
          - containerPort: 8080