apiVersion: apps/v1
kind: Deployment
metadata:
  name: sre-observabilty
spec:
  selector:
      matchLabels:
        app: sre-observabilty
  replicas: 2
  template:
    metadata:
      labels:
        app: sre-observabilty
    spec:
      containers:
        - name: sre-observabilty
          image: rafacamppos/veiculos:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8081

---

apiVersion: v1
kind: Service
metadata:
  name: sre-observabilty-api
  labels:
    app: sre-observabilty-api
spec:
  type: ClusterIP
  ports:
  - port: 81
    protocol: TCP
    targetPort: 81
  selector:
    app: sre-observabilty-api

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sre-observabilty-api
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /aditamento/
        pathType: Prefix
        backend:
          service:
            name: sre-observabilty-api
            port:
              number: 81