apiVersion: apps/v1
kind: Deployment
metadata:
  name: sre-observability
  namespace: argocd
spec:
  selector:
      matchLabels:
        app: sre-observability
  replicas: 5
  template:
    metadata:
      labels:
        app: sre-observability
    spec:
      containers:
        - name: sre-observability
          image: rafacamppos/sre-app
          imagePullPolicy: Always
          ports:
          - containerPort: 8081
          readinessProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 20
          livenessProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 20
          startupProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 30
            failureThreshold: 20