apiVersion: apps/v1
kind: Deployment
metadata:
  name: sre-observabilty
spec:
  selector:
      matchLabels:
        app: sre-observabilty
  replicas: 2
  template:
    metadata:
      labels:
        app: sre-observabilty
    spec:
      containers:
        - name: sre-observabilty
          image: rafacamppos/sre-app
          imagePullPolicy: Always
          ports:
          - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: sre-observabilty-service
spec:
  type: NodePort
  selector:
    app: sre-observabilty
  ports:
  - name: http
    port: 80
    targetPort: 8080
    nodePort: 30005