apiVersion: apps/v1
kind: Deployment
metadata:
  name: sre-observabilty
spec:
  selector:
      matchLabels:
        app: sre-observabilty
  replicas: 2
  template:
    metadata:
      labels:
        app: sre-observabilty
    spec:
      containers:
        - name: sre-observabilty
          image: rafacamppos/veiculos:0.0.1
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
            hostPort: 8080
            name: http
            protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: sre-observabilty
  namespace: argocd
spec:
  type: NodePort
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30080
  selector:
    app: sre-observabilty
  
