apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sre-observability-ingress
  namespace: sre
spec:
    rules:
      - host: sre.observability.rafael.com
        http:
          paths:
          - path: /
            pathType: Prefix  
            backend:
              service:
                name: sre-observability-service
                port:
                 number: 80