apiVersion: v1
kind: Service
metadata:
  name: sre-observabilty-service
  namespace: argocd
spec:
  type: NodePort
  selector:
    app: sre-observabilty
  ports:
  - name: http
    port: 80
    targetPort: 8080
    nodePort: 30005