apiVersion: v1
kind: Service
metadata:
  name: sre-observability-service
  namespace: argocd
spec:
  type: LoadBalancer
  selector:
    app: sre-observability
  ports:
  - name: http
    port: 80
    targetPort: 8080
    nodePort: 30005