management:
    endpoint:
        health:
            enabled: true
            show-details: always
        info:
            enabled: true
        prometheus:
            enabled: true
    endpoints:
        enabled-by-default: false
        web:
            exposure:
                include: info, debug, warning, health, prometheus, metrics
    metrics:
        tags:
            application: spring-actuator
        distribution:
            percentiles[http.server.requests]: 0.5, 0.7, 0.95, 0.99
            percentiles-histogram[http.server.requests]: true
            slo[http.server.requests]: 100ms, 500ms, 1000ms, 1500ms, 2000ms, 2500ms, 3000ms, 3500ms, 4000ms, 4500ms, 5000ms, 5500ms, 6000ms
server:
    port: 8081
spring:
    jackson:
        deserialization:
            fail-on-unknown-properties: true
    jpa:
        properties:
            hibernate:
                generate_statistics: true
url:
    api:
        juros: https://juros-api.itau.br
cloud:
    aws:
        credentials:
            access-key: foo
            secret-key: bar
        sqs:
            order-queue:
                url: http://localhost:4566/000000000000/upload-file-event-sqs
                name: upload-file-event-sqs
        sns:
            order-created:
                arn: arn:aws:sns:eu-central-1:000000000000:order-created-topic
                name: order-created-topic
        stack:
            auto: false
        region:
            static: sa-east-1
logging:
    level:
        com:
            amazonaws:
                util:
                    EC2MetadataUtils: error
