{
 "title": "SRE",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Altera dia pagamento",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{ status!~\"5..\", uri=\"/aditamento/altera-dia-pagamento\"}[$__rate_interval])) by (le))",
     "legendFormat": "p99 - altera_dia_pagamento"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_server_requests_seconds_bucket{ status!~\"5..\", uri=\"/aditamento/altera-dia-pagamento\"}[$__rate_interval])) by (le))",
     "legendFormat": "p90 - altera_dia_pagamento"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_requests_seconds_bucket{ status!~\"5..\", uri=\"/aditamento/altera-dia-pagamento\"}[$__rate_interval])) by (le))",
     "legendFormat": "p50 - altera_dia_pagamento"
    }
   ]
  },
  {
   "title": "Altera Quantidade Parcelas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{ status!~\"5..\", uri=\"/aditamento/altera-quantidade-parcelas\"}[$__rate_interval])) by (le))",
     "legendFormat": "p99 - altera_quantidade_parcela"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_server_requests_seconds_bucket{ status!~\"5..\", uri=\"/aditamento/altera-quantidade-parcelas\"}[$__rate_interval])) by (le))",
     "legendFormat": "p90 - altera_quantidade_parcela"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_requests_seconds_bucket{ status!~\"5..\", uri=\"/aditamento/altera-quantidade-parcelas\"}[$__rate_interval])) by (le))",
     "legendFormat": "p50 - altera_quantidade_parcelas"
    }
   ]
  },
  {
   "title": "API's",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"spring-actuator\", instance=\"host.docker.internal:8080\", job=\"spring-actuator\", status = \"200\", method=\"POST\", uri=\"/aditamento/altera-quantidade-parcelas\"}[$__rate_interval])) / sum(rate(http_server_requests_seconds_count{application=\"spring-actuator\", instance=\"host.docker.internal:8080\", job=\"spring-actuator\", method=\"POST\", uri=\"/aditamento/altera-quantidade-parcelas\"}[$__rate_interval])) * 100",
     "legendFormat": "altera-quantidade-parcelas"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"spring-actuator\", instance=\"host.docker.internal:8080\", job=\"spring-actuator\", status = \"200\", method=\"POST\", uri=\"/aditamento/altera-dia-pagamento\"}[$__rate_interval])) / sum(rate(http_server_requests_seconds_count{application=\"spring-actuator\", instance=\"host.docker.internal:8080\", job=\"spring-actuator\", method=\"POST\", uri=\"/aditamento/altera-dia-pagamento\"}[$__rate_interval])) * 100",
     "legendFormat": "altera-dia-pagamento"
    }
   ]
  },
  {
   "title": "Erros",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(erro_negocio_total{excecao=\"BusinessException\"}[$__rate_interval])",
     "legendFormat": "BusinessException"
    }
   ]
  }
 ]
}